### ISSUE TITLE
Migrate Minions to new master

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/release-mgmt#106]
migrate current minions to the new prod salt master

**Comment by dubb-b** [comment]
A box called ssc is the last to move in C7. 

@Ch3LL or @cachedout are there others you want in the new salt-master and monitored?

**Comment by cachedout** [comment]
I don't have anything to add. Thanks for checking with me though. :]

**Comment by dubb-b** [comment]
CR is going to get me access. This box is not using any password I know of.

**Comment by dubb-b** [comment]
I have access now, will be adding this today.

**Comment by dubb-b** [comment]
Added this to monitoring. Going to close this and setup a new project to move the states of SSC over to new master as another item on its own. Its FreeBSD and I will need a bit of ramp up. The rest of the servers are done.
