### ISSUE TITLE
Create Backups

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/release-mgmt#108]
- [ ] Review and Backup which of the new minions/boxes need backups

**Comment by dubb-b** [comment]
SSC and Zabbix are now being backed up offsite to S3. There is a 30 day retention on them so the bucket doesn't grow out of control. 

@cachedout Would 60 days be better? Can you think of any reason we would need to go back any further?

**Comment by dubb-b** [comment]
Going to leave this open as I want to make sure that nothing breaks and the backups go on schedule. Also, have a bit more saltyness to add to the server.

**Comment by cachedout** [comment]
@dubb-b 30 days is fine with me.

**Comment by dubb-b** [comment]
Backups were not right, I have fixed. Just need to add some code around FreeBSD

**Comment by dubb-b** [comment]
FreeBSD code added and tested. Was part of PR I merged today.
