### ISSUE TITLE
Add Monitoring to Current Minions

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/release-mgmt#109]
- [ ] Add monitoring to the current salt minions attached to old salt master

**Comment by dubb-b** [comment]
Added all the one-node* machines to the new master and installed the zabbix agent and configured it in the UI.

**Comment by dubb-b** [comment]
This is complete. All the minions from thanos are now on new master

**Comment by cachedout** [comment]
Outstanding job, @dubb-b 

Thanks for your amazing work lately!
