### ISSUE TITLE
Create separate branches in salt-jenkins

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/release-mgmt#57]
Create branches in salt-jenkins that mirror the current salt's project branches

**Comment by rallytime** [comment]
Done:
- https://github.com/saltstack/salt-jenkins/tree/2016.11
- https://github.com/saltstack/salt-jenkins/tree/2016.3

For now, we'll keep the `master` branch which will mean that the Jenkins `develop` tests will be be installing the `git.salt` states from the `master` salt-jenkins branch.
