### ISSUE TITLE
Setup production jenkins slaves to point to the new salt-jenkins branches

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/release-mgmt#58]
After creating the salt-jenkins git branches, add them to the gitfs settings in each branch salve

**Comment by rallytime** [comment]
- [ ] 2016.3 node
- [ ] 2016.11 node
- [ ] Figure out how to address this with TCP node. Currently there are 3 jobs (one for each branch) that run on one jenkins node. We can leave this pointed at `master` for now, but this could cause some problems in the future. We might just need one TCP node for each branch? Might need to think this part through a little better.

**Comment by rallytime** [comment]
I have moved that last checklist item to a new issue, since that was something that occurred to me during this process and can be addressed later. Since the regular branch nodes are all configured properly now in Jenkins, I'll close this.
