### ISSUE TITLE
Pypi package proxy / Reduce failures on 3rd party package issues

### ISSUE THREAD

**Issue by dubb-b** [saltstack/release-mgmt#6]
Get metrics for failure rate external resources so that we can identify where failures are. 

Create a proxied solution for 3rd party artifacts.

Proposed solutions:
Artifact Repository Tool added to the environment to cache local packages

**Comment by s0undt3ch** [comment]
We used to have a devpi proxy/cache server or pypi for which the salt Jenkins state tree is still prepared to use.

Its just a matter of setting up a new instance (this time in C7) and point the DNS to it.

**Comment by dubb-b** [comment]
Have you used Nexus as a proxy before @s0undt3ch ?
