### ISSUE TITLE
Documentation of Zabbix

### ISSUE THREAD

**Issue by dubb-b** [saltstack/release-mgmt#89]
Add the zabbix documentation to the Wiki

**Comment by dubb-b** [comment]
Documented the Server and Agent setup on the wiki.
This document may change over time due to the changes in infrastructure.

**Comment by dubb-b** [comment]
@cachedout 

Here is the issue I created for documentation of Zabbix

**Comment by cachedout** [comment]
@dubb-b Perfect. Thanks. Commented over on the other issue. We're good now. Thanks. :]
