### ISSUE TITLE
Add Zabbix to IPA and configure users

### ISSUE THREAD

**Issue by dubb-b** [saltstack/release-mgmt#90]
Add the Zabbix server to IPA and configure all the users that need access.

**Comment by dubb-b** [comment]
IPA is the authentication method for Zabbix now. The Admin local creds are in the password doc.

**Comment by dubb-b** [comment]
@cachedout @cro @Ch3LL are all admins.

**Comment by cachedout** [comment]
Docs on the zabbix server needed at all? If so, please put in zh wiki and make issue to track it. Otherwise, this looks good. Really nice job here, @dubb-b !

**Comment by dubb-b** [comment]
I put it in wiki here: https://github.com/saltstack/release-mgmt/wiki/Monitoring

Do you think it would be better in zh?

**Comment by cachedout** [comment]
@dubb-b No, you're right on this one. We actually discussed this and I forgot. Thanks for catching that!
