### ISSUE TITLE
Add Salt Minions to anything in C7 that needs to be managed

### ISSUE THREAD

**Issue by dubb-b** [saltstack/release-mgmt#93]
Add salt-minion and point it to the new salt-master for all the infrastructure items that need salt to manage them.

Add Zabbix to all these hosts.

**Comment by dubb-b** [comment]
Since we started from scratch we need to determine how to migrate the states over that are there. I talked to CR a bit. For now i may just add my state code to thanos for the zabbix agents. Still thinking on this....

**Comment by Ch3LL** [comment]
Creating epic for this instead
